(define (problem task)
(:domain turtlebot_demo)
(:objects
    wp0 wp1 wp2 wp3 - waypoint
    kenny - robot
    dougnut_1 dougnut_2 dougnut_3 dougnut_4 dougnut_5 dougnut_6 dougnut_7 dougnut_8 dougnut_9 dougnut_10 dougnut_11 dougnut_12 dougnut_13 dougnut_14 dougnut_15 dougnut_16 dougnut_17 dougnut_18 dougnut_19 dougnut_20 dougnut_21 dougnut_22 dougnut_23 dougnut_24 - doughnut
    order_0 order_1 order_2 order_3 - order
)
(:init
    (robot_at kenny wp0)



    (not_inspected dougnut_1)
    (not_inspected dougnut_2)
    (not_inspected dougnut_3)
    (not_inspected dougnut_4)
    (not_inspected dougnut_5)
    (not_inspected dougnut_6)
    (not_inspected dougnut_7)
    (not_inspected dougnut_8)
    (not_inspected dougnut_9)
    (not_inspected dougnut_10)
    (not_inspected dougnut_11)
    (not_inspected dougnut_12)
    (not_inspected dougnut_13)
    (not_inspected dougnut_14)
    (not_inspected dougnut_15)
    (not_inspected dougnut_16)
    (not_inspected dougnut_17)
    (not_inspected dougnut_18)
    (not_inspected dougnut_19)
    (not_inspected dougnut_20)
    (not_inspected dougnut_21)
    (not_inspected dougnut_22)
    (not_inspected dougnut_23)
    (not_inspected dougnut_24)

    (doughnut_visible_from wp3 dougnut_20)
    (doughnut_visible_from wp2 dougnut_24)
    (doughnut_visible_from wp3 dougnut_13)
    (doughnut_visible_from wp1 dougnut_24)

    (part_of dougnut_1 order_0)
    (part_of dougnut_2 order_0)
    (part_of dougnut_3 order_0)
    (part_of dougnut_4 order_0)
    (part_of dougnut_5 order_0)
    (part_of dougnut_6 order_0)
    (part_of dougnut_7 order_1)
    (part_of dougnut_8 order_1)
    (part_of dougnut_9 order_1)
    (part_of dougnut_10 order_1)
    (part_of dougnut_11 order_1)
    (part_of dougnut_12 order_1)
    (part_of dougnut_13 order_2)
    (part_of dougnut_14 order_2)
    (part_of dougnut_15 order_2)
    (part_of dougnut_16 order_2)
    (part_of dougnut_17 order_2)
    (part_of dougnut_18 order_2)
    (part_of dougnut_19 order_3)
    (part_of dougnut_20 order_3)
    (part_of dougnut_21 order_3)
    (part_of dougnut_22 order_3)
    (part_of dougnut_23 order_3)
    (part_of dougnut_24 order_3)

    (= (distance wp0 wp1) 1.6)
    (= (distance wp1 wp0) 1.6)
    (= (distance wp1 wp2) 1.6)
    (= (distance wp1 wp3) 1.6)
    (= (distance wp2 wp1) 1.6)
    (= (distance wp3 wp1) 1.6)

    (= (order_complete order_0) 0)
    (= (order_complete order_1) 0)
    (= (order_complete order_2) 0)
    (= (order_complete order_3) 0)

)
(:goal (and
    (>=  (order_complete order_0) 6)
))
)
